version: '2.4'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7.25
    volumes:
      - ./sql-data/db:/var/lib/mysql
    ports:
      - '3306:3306'
    hostname: localhost
    environment:
      MYSQL_DATABASE: 'personas'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'